// CLI concerns: argv parsing, --help text, upfront validation of the
// trace directory, and the stderr progress log that shows file sizes.

import { existsSync, statSync } from "node:fs";
import { join } from "node:path";
import { formatBytes } from "./util.mjs";

export function printHelp() {
  const lines = [
    "tsc-trace-analyzer — parse tsc --generateTrace output into a structured report",
    "",
    "Usage:",
    "  node analyze-trace.mjs <traceDir> [--top N] [--cwd <projectRoot>]",
    "",
    "Arguments:",
    "  <traceDir>           Directory generated by `tsc --generateTrace`.",
    "                       Must contain at least one trace.json file.",
    "",
    "Options:",
    "  --top N              Number of hotspots to report (default: 15)",
    "  --cwd <projectRoot>  Project root used to resolve paths to relative form",
    "                       (default: current working directory)",
    "  -h, --help           Show this help and exit",
    "",
    "Output:",
    "  JSON is written to stdout. Progress messages go to stderr, so",
    "  you can safely redirect stdout (e.g. `… > report.json`).",
  ];
  console.error(lines.join("\n"));
}

export function parseArgs(argv) {
  const args = argv.slice(2);
  if (args.length === 0 || args.includes("--help") || args.includes("-h")) {
    printHelp();
    process.exit(args.length === 0 ? 1 : 0);
  }

  const traceDir = args[0];
  let topN = 15;
  let projectRoot = process.cwd();

  for (let i = 1; i < args.length; i++) {
    if (args[i] === "--top" && args[i + 1]) {
      topN = parseInt(args[i + 1], 10);
      i++;
    } else if (args[i] === "--cwd" && args[i + 1]) {
      projectRoot = args[i + 1];
      i++;
    }
  }

  return { traceDir, topN, projectRoot };
}

export function validateTraceDir(traceDir) {
  if (!existsSync(traceDir)) {
    console.error(
      `Error: trace directory not found: ${traceDir}\n` +
        `Hint: did \`tsc --generateTrace "${traceDir}"\` actually run and finish?`
    );
    process.exit(1);
  }

  try {
    if (!statSync(traceDir).isDirectory()) {
      console.error(
        `Error: ${traceDir} exists but is not a directory.\n` +
          `Hint: pass the directory you gave to --generateTrace, not an individual trace file.`
      );
      process.exit(1);
    }
  } catch (err) {
    console.error(`Error: cannot read ${traceDir}: ${err.message}`);
    process.exit(1);
  }
}

export function printTraceFileSizes(traceDir, traceFiles, typesFiles) {
  const bold = "\x1b[1m";
  const dim = "\x1b[2m";
  const reset = "\x1b[0m";
  console.error(`${bold}Reading trace files from ${traceDir}${reset}`);
  let grandTotal = 0;
  const rows = [];
  for (const f of [...traceFiles, ...typesFiles]) {
    try {
      const size = statSync(join(traceDir, f)).size;
      grandTotal += size;
      rows.push({ f, size });
    } catch {
      rows.push({ f, size: null });
    }
  }
  // Figure out width for right-aligned sizes
  const sizeStrs = rows.map((r) => (r.size == null ? "?" : formatBytes(r.size)));
  const width = Math.max(...sizeStrs.map((s) => s.length));
  rows.forEach((r, i) => {
    const padded = sizeStrs[i].padStart(width);
    console.error(`  ${bold}${padded}${reset}  ${dim}${r.f}${reset}`);
  });
  console.error(
    `  ${bold}${formatBytes(grandTotal).padStart(width)}${reset}  ${dim}total${reset}`
  );
  console.error("");
}
