#!/usr/bin/env node

// TypeScript compiler trace analyzer
// Parses tsc --generateTrace output and produces structured JSON for Claude to analyze.
// Zero dependencies — uses only Node.js built-ins.

import { readFileSync, readdirSync, existsSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { platform } from "node:os";

// --- CLI argument parsing ---

function printHelp() {
  const lines = [
    "tsc-trace-analyzer — parse tsc --generateTrace output into a structured report",
    "",
    "Usage:",
    "  node analyze-trace.mjs <traceDir> [--top N] [--cwd <projectRoot>]",
    "",
    "Arguments:",
    "  <traceDir>           Directory generated by `tsc --generateTrace`.",
    "                       Must contain at least one trace.json file.",
    "",
    "Options:",
    "  --top N              Number of hotspots to report (default: 15)",
    "  --cwd <projectRoot>  Project root used to resolve paths to relative form",
    "                       (default: current working directory)",
    "  -h, --help           Show this help and exit",
    "",
    "Output:",
    "  JSON is written to stdout. Progress messages go to stderr, so",
    "  you can safely redirect stdout (e.g. `… > report.json`).",
  ];
  console.error(lines.join("\n"));
}

const args = process.argv.slice(2);
if (args.length === 0 || args.includes("--help") || args.includes("-h")) {
  printHelp();
  process.exit(args.length === 0 ? 1 : 0);
}

const traceDir = args[0];
let topN = 15;
let projectRoot = process.cwd();

for (let i = 1; i < args.length; i++) {
  if (args[i] === "--top" && args[i + 1]) {
    topN = parseInt(args[i + 1], 10);
    i++;
  } else if (args[i] === "--cwd" && args[i + 1]) {
    projectRoot = args[i + 1];
    i++;
  }
}

// --- Validate traceDir upfront ---

if (!existsSync(traceDir)) {
  console.error(
    `Error: trace directory not found: ${traceDir}\n` +
      `Hint: did \`tsc --generateTrace "${traceDir}"\` actually run and finish?`
  );
  process.exit(1);
}

try {
  if (!statSync(traceDir).isDirectory()) {
    console.error(
      `Error: ${traceDir} exists but is not a directory.\n` +
        `Hint: pass the directory you gave to --generateTrace, not an individual trace file.`
    );
    process.exit(1);
  }
} catch (err) {
  console.error(`Error: cannot read ${traceDir}: ${err.message}`);
  process.exit(1);
}

// --- Find trace files ---

function findTraceFiles(dir) {
  const files = readdirSync(dir);
  const traceFiles = files
    .filter((f) => /^trace(\.\d+)?\.json$/.test(f))
    .sort();
  const typesFiles = files
    .filter((f) => /^types(\.\d+)?\.json$/.test(f))
    .sort();
  return { traceFiles, typesFiles };
}

const { traceFiles, typesFiles } = findTraceFiles(traceDir);

if (traceFiles.length === 0) {
  console.error(
    `Error: no trace.json files found in ${traceDir}\n` +
      `Hint: expected files like trace.json / types.json (optionally numbered). ` +
      `Did tsc crash before writing the trace?`
  );
  process.exit(1);
}

// --- Progress: report what we're about to read ---

function formatBytes(n) {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  if (n < 1024 * 1024 * 1024) return `${(n / 1024 / 1024).toFixed(1)} MB`;
  return `${(n / 1024 / 1024 / 1024).toFixed(2)} GB`;
}

(function logTraceFileSizes() {
  const bold = "\x1b[1m";
  const dim = "\x1b[2m";
  const reset = "\x1b[0m";
  console.error(`${bold}Reading trace files from ${traceDir}${reset}`);
  let grandTotal = 0;
  const rows = [];
  for (const f of [...traceFiles, ...typesFiles]) {
    try {
      const size = statSync(join(traceDir, f)).size;
      grandTotal += size;
      rows.push({ f, size });
    } catch {
      rows.push({ f, size: null });
    }
  }
  // Figure out width for right-aligned sizes
  const sizeStrs = rows.map((r) => (r.size == null ? "?" : formatBytes(r.size)));
  const width = Math.max(...sizeStrs.map((s) => s.length));
  rows.forEach((r, i) => {
    const padded = sizeStrs[i].padStart(width);
    console.error(`  ${bold}${padded}${reset}  ${dim}${r.f}${reset}`);
  });
  console.error(
    `  ${bold}${formatBytes(grandTotal).padStart(width)}${reset}  ${dim}total${reset}`
  );
  console.error("");
})();

// --- Line map cache for offset→line:col conversion ---

const lineMapCache = new Map();

function getLineMap(filePath) {
  if (lineMapCache.has(filePath)) return lineMapCache.get(filePath);
  try {
    const text = readFileSync(filePath, "utf-8");
    const lineStarts = [0];
    for (let i = 0; i < text.length; i++) {
      if (text.charCodeAt(i) === 10) {
        lineStarts.push(i + 1);
      }
    }
    const entry = { lineStarts, text };
    lineMapCache.set(filePath, entry);
    return entry;
  } catch {
    return null;
  }
}

function offsetToLineCol(lineStarts, offset) {
  let lo = 0;
  let hi = lineStarts.length - 1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (lineStarts[mid] <= offset) lo = mid;
    else hi = mid - 1;
  }
  return { line: lo + 1, col: offset - lineStarts[lo] + 1 };
}

function resolveLocation(filePath, pos, end) {
  const map = getLineMap(filePath);
  if (!map) return null;
  const start = offsetToLineCol(map.lineStarts, pos);
  const endLoc = offsetToLineCol(map.lineStarts, end);
  return { line: start.line, col: start.col, endLine: endLoc.line, endCol: endLoc.col };
}

function extractSnippet(filePath, pos, end) {
  const map = getLineMap(filePath);
  if (!map) return null;
  const maxLen = 150;
  const snippetEnd = Math.min(end, pos + maxLen);
  let snippet = map.text.slice(pos, snippetEnd).replace(/\s+/g, " ").trim();
  if (end > snippetEnd) snippet += "...";
  return snippet;
}

// --- Parse types.json ---

function loadTypes(typesFile) {
  const typesMap = new Map();
  if (!typesFile || !existsSync(typesFile)) return typesMap;
  try {
    const types = JSON.parse(readFileSync(typesFile, "utf-8"));
    for (const t of types) {
      typesMap.set(t.id, t);
    }
  } catch {
    // types.json may be malformed or missing
  }
  return typesMap;
}

// --- Parse trace.json and build spans ---

function parseTrace(traceFile) {
  const raw = readFileSync(traceFile, "utf-8");
  let events;
  try {
    events = JSON.parse(raw);
  } catch {
    // Try to handle truncated JSON (common with large traces)
    const trimmed = raw.replace(/,?\s*$/, "]");
    events = JSON.parse(trimmed);
  }

  const spans = [];
  const stack = [];
  // Track top-level phase durations from specific marker events only
  const phaseTimes = { parse: 0, bind: 0, check: 0, emit: 0 };
  const phaseMarkers = {
    checkSourceFile: "check",
    bindSourceFile: "bind",
    parseSourceFile: "parse",
    createSourceFile: "parse",
    emitDeclarationFileOrBundle: "emit",
    emitJsFileOrBundle: "emit",
    emit: "emit",
  };
  const filesChecked = new Set();

  for (const ev of events) {
    if (ev.ph === "X") {
      // Complete event — has dur field (in microseconds)
      const durMs = ev.dur / 1000;
      const cat = ev.cat || "";

      // Only count top-level phase markers to avoid double-counting
      if (ev.name in phaseMarkers) {
        phaseTimes[phaseMarkers[ev.name]] += durMs;
      }

      const filePath = ev.args?.path;
      if (filePath) filesChecked.add(filePath);

      spans.push({
        name: ev.name,
        cat,
        durMs,
        file: filePath || null,
        pos: ev.args?.pos,
        end: ev.args?.end,
        args: ev.args || {},
      });
    } else if (ev.ph === "B") {
      stack.push(ev);
    } else if (ev.ph === "E") {
      const begin = stack.pop();
      if (begin) {
        const durMs = (ev.ts - begin.ts) / 1000;
        const cat = begin.cat || ev.cat || "";
        const name = begin.name || ev.name;

        if (name in phaseMarkers) {
          phaseTimes[phaseMarkers[name]] += durMs;
        }

        const mergedArgs = { ...begin.args, ...ev.args };
        const filePath = mergedArgs.path;
        if (filePath) filesChecked.add(filePath);

        spans.push({
          name,
          cat,
          durMs,
          file: filePath || null,
          pos: mergedArgs.pos,
          end: mergedArgs.end,
          args: mergedArgs,
        });
      }
    }
  }

  return { spans, phaseTimes, filesChecked };
}

// --- Aggregate results ---

// Container/wrapper events that aren't directly actionable on their own
const CONTAINER_EVENTS = new Set([
  "createProgram",
  "processRootFiles",
  "findSourceFile",
  "emit",
  "printSourceFile",
]);

function analyzeSpans(spans, typesMap) {
  // Top N individual spans by duration, excluding broad container events
  const topSpans = spans
    .filter((s) => s.durMs > 0 && !CONTAINER_EVENTS.has(s.name))
    .sort((a, b) => b.durMs - a.durMs)
    .slice(0, topN);

  // Aggregate check time by file
  const fileTimeMap = new Map();
  for (const s of spans) {
    if (s.cat === "check" && s.file) {
      fileTimeMap.set(s.file, (fileTimeMap.get(s.file) || 0) + s.durMs);
    }
  }

  const totalCheckMs = Array.from(fileTimeMap.values()).reduce(
    (a, b) => a + b,
    0
  );

  const hotspotsByFile = Array.from(fileTimeMap.entries())
    .map(([file, ms]) => ({
      file: tryRelative(file),
      totalCheckMs: round(ms),
      percentOfTotal: totalCheckMs > 0 ? round((ms / totalCheckMs) * 100) : 0,
    }))
    .sort((a, b) => b.totalCheckMs - a.totalCheckMs)
    .slice(0, topN);

  // Build detailed hotspot entries
  const hotspotsBySpan = topSpans.map((s, i) => {
    const entry = {
      rank: i + 1,
      event: s.name,
      category: s.cat,
      durationMs: round(s.durMs),
      file: s.file ? tryRelative(s.file) : null,
      location: null,
      snippet: null,
    };

    if (s.file && s.pos != null && s.end != null) {
      entry.location = resolveLocation(s.file, s.pos, s.end);
      entry.snippet = extractSnippet(s.file, s.pos, s.end);
    }

    // Resolve type info for type-related events
    if (s.args.sourceId != null && typesMap.has(s.args.sourceId)) {
      entry.sourceType = formatType(typesMap.get(s.args.sourceId));
    }
    if (s.args.targetId != null && typesMap.has(s.args.targetId)) {
      entry.targetType = formatType(typesMap.get(s.args.targetId));
    }
    if (
      s.args.id != null &&
      !entry.sourceType &&
      typesMap.has(s.args.id)
    ) {
      entry.type = formatType(typesMap.get(s.args.id));
    }

    return entry;
  });

  return { hotspotsByFile, hotspotsBySpan };
}

function formatType(typeEntry) {
  if (!typeEntry) return null;
  const result = {
    id: typeEntry.id,
    name: typeEntry.symbolName || typeEntry.display || `type#${typeEntry.id}`,
  };
  if (typeEntry.firstDeclaration) {
    result.declarationFile = tryRelative(typeEntry.firstDeclaration.path);
    if (
      typeEntry.firstDeclaration.start != null &&
      typeEntry.firstDeclaration.end != null
    ) {
      const loc = resolveLocation(
        typeEntry.firstDeclaration.path,
        typeEntry.firstDeclaration.start,
        typeEntry.firstDeclaration.end
      );
      if (loc) result.declarationLine = loc.line;
    }
  }
  return result;
}

// --- Detect duplicate packages ---

function detectDuplicatePackages(filesChecked) {
  const packagePaths = new Map();
  for (const f of filesChecked) {
    const nmIdx = f.lastIndexOf("node_modules/");
    if (nmIdx === -1) continue;
    const afterNm = f.slice(nmIdx + "node_modules/".length);
    let pkgName;
    if (afterNm.startsWith("@")) {
      const parts = afterNm.split("/");
      pkgName = parts[0] + "/" + parts[1];
    } else {
      pkgName = afterNm.split("/")[0];
    }
    const pkgDir = f.slice(0, nmIdx + "node_modules/".length + pkgName.length);
    if (!packagePaths.has(pkgName)) packagePaths.set(pkgName, new Set());
    packagePaths.get(pkgName).add(tryRelative(pkgDir));
  }

  return Array.from(packagePaths.entries())
    .filter(([, paths]) => paths.size > 1)
    .map(([name, paths]) => ({ name, paths: Array.from(paths) }));
}

// --- Utilities ---

function round(n) {
  return Math.round(n * 10) / 10;
}

const isCaseInsensitiveFS = platform() === "darwin" || platform() === "win32";

function normalizePath(p) {
  return isCaseInsensitiveFS ? p.toLowerCase() : p;
}

function tryRelative(filePath) {
  if (!filePath) return filePath;
  try {
    // On case-insensitive filesystems, trace paths may differ in case from cwd
    const rel = isCaseInsensitiveFS
      ? relative(normalizePath(projectRoot), normalizePath(filePath))
      : relative(projectRoot, filePath);
    return rel.startsWith("..") ? filePath : rel;
  } catch {
    return filePath;
  }
}

// --- Main ---

function main() {
  let allSpans = [];
  let totalPhaseTimes = { parse: 0, bind: 0, check: 0, emit: 0 };
  let allFilesChecked = new Set();
  let typesMap = new Map();

  for (let i = 0; i < traceFiles.length; i++) {
    const tracePath = join(traceDir, traceFiles[i]);
    const { spans, phaseTimes, filesChecked } = parseTrace(tracePath);

    allSpans = allSpans.concat(spans);
    for (const [k, v] of Object.entries(phaseTimes)) {
      totalPhaseTimes[k] += v;
    }
    for (const f of filesChecked) allFilesChecked.add(f);

    // Load corresponding types file if it exists
    if (typesFiles[i]) {
      const tMap = loadTypes(join(traceDir, typesFiles[i]));
      for (const [id, t] of tMap) typesMap.set(id, t);
    }
  }

  const totalTimeMs =
    totalPhaseTimes.parse +
    totalPhaseTimes.bind +
    totalPhaseTimes.check +
    totalPhaseTimes.emit;

  const { hotspotsByFile, hotspotsBySpan } = analyzeSpans(allSpans, typesMap);
  const duplicatePackages = detectDuplicatePackages(allFilesChecked);

  const output = {
    summary: {
      totalTimeMs: round(totalTimeMs),
      parseMs: round(totalPhaseTimes.parse),
      bindMs: round(totalPhaseTimes.bind),
      checkMs: round(totalPhaseTimes.check),
      emitMs: round(totalPhaseTimes.emit),
      fileCount: allFilesChecked.size,
    },
    hotspotsByFile,
    hotspotsBySpan,
    duplicatePackages,
  };

  console.log(JSON.stringify(output, null, 2));
}

main();
